services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/weather_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Catalin.21
    ports:
      - "6000:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
      - db-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Catalin.21
      MYSQL_DATABASE: weather_db
    ports:
      - "3306:3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root --password=Catalin.21",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - db-network

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: Catalin.21
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db-network

networks:
  app-network:
    driver: bridge
  db-network:
    driver: bridge
